package source

import "testing"

// TestDiscoverGeneratedHeaderVariants verifies generated-file detection accepts
// common tool headers that include both generated provenance and DO NOT EDIT.
func TestDiscoverGeneratedHeaderVariants(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "cli/generated.go", "// Generated by CLI Printing Press from schema. DO NOT EDIT.\npackage cli\n")
	writeFile(t, root, "api/generated.go", "// AUTO-GENERATED FROM openapi.yaml - DO NOT EDIT.\npackage api\n")
	writeFile(t, root, "block/generated.go", "/*\nGenerated by toolchain.\nDO NOT EDIT.\n*/\npackage block\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	if got := paths(result.Files); len(got) != 0 {
		t.Fatalf("generated files should be skipped, got files %#v", got)
	}
	for _, want := range []string{
		"api/generated.go:generated",
		"block/generated.go:generated",
		"cli/generated.go:generated",
	} {
		if !contains(skippedReasons(result.Skipped), want) {
			t.Fatalf("skipped reasons %#v missing %q", skippedReasons(result.Skipped), want)
		}
	}
}

// TestDiscoverGeneratedHeaderRequiresBothMarkers keeps hand-written files that
// merely mention "do not edit" or "generated" inside the analysable set.
func TestDiscoverGeneratedHeaderRequiresBothMarkers(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "manual/comment.go", "// DO NOT EDIT these fixtures without updating tests.\npackage manual\n")
	writeFile(t, root, "manual/string.go", "package manual\n\nconst warning = \"do not edit this database row manually\"\n")
	writeFile(t, root, "manual/generated_only.go", "// Generated values are documented here.\npackage manual\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	want := []string{"manual/comment.go", "manual/generated_only.go", "manual/string.go"}
	if got := paths(result.Files); !equal(got, want) {
		t.Fatalf("files = %#v, want %#v", got, want)
	}
	if len(result.Skipped) != 0 {
		t.Fatalf("counter-fixtures should not be skipped, got %#v", result.Skipped)
	}
}
