// Package source tests exercise Discover across classification and ignore rules.
// They construct temp directory trees and assert files, skips, and missing paths.
package source

import (
	"os"
	"path/filepath"
	"testing"
)

// TestDiscoverClassifiesAndSkipsDefaultIgnoredPaths verifies built-in ignored directories.
func TestDiscoverClassifiesAndSkipsDefaultIgnoredPaths(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "main.go", "package main\n")
	writeFile(t, root, "config.yaml", "name: demo\n")
	writeFile(t, root, "generated/generated.go", "// Code generated by test. DO NOT EDIT.\npackage generated\n")
	writeFile(t, root, "vendor/pkg/vendor.go", "package pkg\n")
	writeFile(t, root, ".agents/skills/tool/config.yaml", "name: ignored\n")
	writeFile(t, root, ".claude/settings.json", "{}\n")
	writeFile(t, root, ".codex/config.toml", "model = \"codex\"\n")
	writeFile(t, root, ".github/workflows/ci.yml", "name: ci\n")
	writeFile(t, root, ".goat-flow/config.yaml", "version: 1\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	gotFiles := paths(result.Files)
	wantFiles := []string{"config.yaml", "main.go"}
	if !equal(gotFiles, wantFiles) {
		t.Fatalf("files = %#v, want %#v", gotFiles, wantFiles)
	}

	gotSkipped := skippedReasons(result.Skipped)
	for _, want := range []string{
		"generated/generated.go:generated",
		"vendor:dependency",
		".agents:non-application-metadata",
		".claude:non-application-metadata",
		".codex:non-application-metadata",
		".github:non-application-metadata",
		".goat-flow:non-application-metadata",
	} {
		if !contains(gotSkipped, want) {
			t.Fatalf("skipped reasons %#v missing %q", gotSkipped, want)
		}
	}
}

// TestDiscoverRespectsGitignoreWithNegation exercises gitignore matching including negation.
func TestDiscoverRespectsGitignoreWithNegation(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".gitignore", "bin/*\n!bin/keeper.go\n*.log\n")
	writeFile(t, root, "main.go", "package main\n")
	writeFile(t, root, "bin/keeper.go", "package keeper\n")
	writeFile(t, root, "bin/scratch.go", "package scratch\n")
	writeFile(t, root, "notes.log", "noise\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	got := paths(result.Files)
	want := []string{"bin/keeper.go", "main.go"}
	if !equal(got, want) {
		t.Fatalf("files = %#v, want %#v", got, want)
	}

	gotSkipped := skippedReasons(result.Skipped)
	for _, want := range []string{
		"bin/scratch.go:gitignored",
		"notes.log:gitignored",
	} {
		if !contains(gotSkipped, want) {
			t.Fatalf("skipped reasons %#v missing %q", gotSkipped, want)
		}
	}
}

// TestDiscoverGitignoreNestedOverride verifies nested .gitignore files override parent patterns.
func TestDiscoverGitignoreNestedOverride(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".gitignore", "*.tmp\n")
	writeFile(t, root, "pkg/.gitignore", "!keep.tmp\n")
	writeFile(t, root, "pkg/keep.tmp", "ignored content\n")
	writeFile(t, root, "pkg/throwaway.tmp", "ignored content\n")
	writeFile(t, root, "pkg/main.go", "package pkg\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	// Note: *.tmp matches both keep.tmp and throwaway.tmp; pkg/.gitignore
	// !keep.tmp re-includes keep.tmp. throwaway.tmp stays gitignored.
	got := paths(result.Files)
	wantContains := []string{"pkg/main.go"}
	for _, w := range wantContains {
		if !contains(got, w) {
			t.Fatalf("files = %#v missing %q", got, w)
		}
	}
	// keep.tmp is re-included by negation but .tmp is not a recognised source
	// extension; the classifier drops it. So it should not appear in Files,
	// and should NOT appear in Skipped with reason gitignored either.
	if contains(skippedReasons(result.Skipped), "pkg/keep.tmp:gitignored") {
		t.Fatalf("pkg/keep.tmp should not be in skipped:gitignored after negation; got %#v", result.Skipped)
	}
	if !contains(skippedReasons(result.Skipped), "pkg/throwaway.tmp:gitignored") {
		t.Fatalf("pkg/throwaway.tmp should be skipped:gitignored; got %#v", result.Skipped)
	}
}

// TestDiscoverIncludeIgnoredBypassesGitignore verifies --include-ignored disables gitignore filtering.
func TestDiscoverIncludeIgnoredBypassesGitignore(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".gitignore", "secret.go\n")
	writeFile(t, root, "secret.go", "package secret\n")
	writeFile(t, root, "main.go", "package main\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}, IncludeIgnored: true})
	if err != nil {
		t.Fatal(err)
	}

	got := paths(result.Files)
	want := []string{"main.go", "secret.go"}
	if !equal(got, want) {
		t.Fatalf("files = %#v, want %#v", got, want)
	}
	for _, item := range result.Skipped {
		if item.Reason == "gitignored" {
			t.Fatalf("--include-ignored must not emit gitignored skipped entries; got %#v", item)
		}
	}
}

// TestDiscoverIncludeIgnoredPreservesConfigIgnores verifies config-level ignores survive --include-ignored.
func TestDiscoverIncludeIgnoredPreservesConfigIgnores(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".gitignore", "secret.go\n")
	writeFile(t, root, "secret.go", "package secret\n")
	writeFile(t, root, "main.go", "package main\n")

	result, err := Discover(Options{
		Root:           root,
		Paths:          []string{"."},
		IncludeIgnored: true,
		IgnorePatterns: []string{"secret.go"},
	})
	if err != nil {
		t.Fatal(err)
	}

	got := paths(result.Files)
	if !equal(got, []string{"main.go"}) {
		t.Fatalf("files = %#v, want only main.go", got)
	}
	if !contains(skippedReasons(result.Skipped), "secret.go:config-ignore") {
		t.Fatalf("secret.go should remain config-ignored with --include-ignored; got %#v", result.Skipped)
	}
}

// TestDiscoverRootGitignoreOwnsFallbackDirectories verifies projects own vendor when .gitignore exists.
func TestDiscoverRootGitignoreOwnsFallbackDirectories(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".gitignore", "# project owns vendor\n")
	writeFile(t, root, "main.go", "package main\n")
	writeFile(t, root, "vendor/pkg/vendor.go", "package pkg\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	got := paths(result.Files)
	want := []string{"main.go", "vendor/pkg/vendor.go"}
	if !equal(got, want) {
		t.Fatalf("files = %#v, want %#v", got, want)
	}
	if contains(skippedReasons(result.Skipped), "vendor:dependency") {
		t.Fatalf("vendor should not be hardcoded-skipped when root .gitignore exists: %#v", result.Skipped)
	}
}

// TestDiscoverExplicitIgnoredInputDirectoryPrunes verifies explicit ignored input directories are pruned.
func TestDiscoverExplicitIgnoredInputDirectoryPrunes(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "node_modules/pkg/index.go", "package pkg\n")

	result, err := Discover(Options{Root: root, Paths: []string{"node_modules"}})
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Files) != 0 {
		t.Fatalf("files = %#v, want no files from ignored input directory", result.Files)
	}
	gotSkipped := skippedReasons(result.Skipped)
	if !contains(gotSkipped, "node_modules:dependency") {
		t.Fatalf("node_modules input should be skipped as a directory; got %#v", gotSkipped)
	}
	if contains(gotSkipped, "node_modules/pkg/index.go:dependency") {
		t.Fatalf("node_modules should be pruned before per-file skips; got %#v", gotSkipped)
	}
}

// TestDiscoverExplicitNonApplicationMetadataFileSkipped verifies metadata files are skipped explicitly.
func TestDiscoverExplicitNonApplicationMetadataFileSkipped(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".codex/config.toml", "model = \"codex\"\n")

	result, err := Discover(Options{Root: root, Paths: []string{".codex/config.toml"}})
	if err != nil {
		t.Fatal(err)
	}

	if len(result.Files) != 0 {
		t.Fatalf("files = %#v, want no files from non-application metadata", result.Files)
	}
	gotSkipped := skippedReasons(result.Skipped)
	if !contains(gotSkipped, ".codex/config.toml:non-application-metadata") {
		t.Fatalf("explicit metadata file should be skipped; got %#v", gotSkipped)
	}
}

// TestDiscoverNoGitignoreFallsBackToHardcoded verifies fallback skips when no .gitignore is present.
func TestDiscoverNoGitignoreFallsBackToHardcoded(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "main.go", "package main\n")
	writeFile(t, root, "vendor/pkg/vendor.go", "package pkg\n")
	writeFile(t, root, "node_modules/lib/index.js", "x")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	got := paths(result.Files)
	if !equal(got, []string{"main.go"}) {
		t.Fatalf("files = %#v, want [main.go]", got)
	}
	gotSkipped := skippedReasons(result.Skipped)
	for _, want := range []string{"vendor:dependency", "node_modules:dependency"} {
		if !contains(gotSkipped, want) {
			t.Fatalf("hardcoded fallback skip missing %q in %#v", want, gotSkipped)
		}
	}
}

// TestDiscoverMalformedGitignore verifies malformed .gitignore files are surfaced as diagnostics.
func TestDiscoverMalformedGitignore(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, ".gitignore", "*.log\n[bad\n")
	writeFile(t, root, "main.go", "package main\n")
	writeFile(t, root, "scratch.log", "noise\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	// Malformed .gitignore: rules dropped, file flagged in Skipped.
	if !contains(paths(result.Files), "main.go") {
		t.Fatalf("main.go should still be scanned despite malformed gitignore")
	}
	if !contains(skippedReasons(result.Skipped), ".gitignore:gitignore-parse-error") {
		t.Fatalf("malformed .gitignore must be reported with reason gitignore-parse-error; got %#v", result.Skipped)
	}
}

// TestDiscoverRecordsMissingInputs verifies missing input paths are reported as missing.
func TestDiscoverRecordsMissingInputs(t *testing.T) {
	root := t.TempDir()
	result, err := Discover(Options{Root: root, Paths: []string{"missing.go"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Missing) != 1 || result.Missing[0] != "missing.go" {
		t.Fatalf("missing = %#v, want missing.go", result.Missing)
	}
}

// writeFile writes contents to root/rel, creating parent directories as needed.
func writeFile(t *testing.T, root, rel, contents string) {
	t.Helper()
	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}

// paths returns the relative path of each discovered file.
func paths(files []File) []string {
	out := make([]string, 0, len(files))
	for _, file := range files {
		out = append(out, file.Path)
	}
	return out
}

// skippedReasons formats skipped entries as "path:reason" strings for assertions.
func skippedReasons(skipped []SkippedPath) []string {
	out := make([]string, 0, len(skipped))
	for _, item := range skipped {
		out = append(out, item.Path+":"+item.Reason)
	}
	return out
}

// equal reports whether two string slices have identical contents in order.
func equal(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

// contains reports whether the slice includes the given value.
func contains(values []string, value string) bool {
	for _, current := range values {
		if current == value {
			return true
		}
	}
	return false
}
