package source

import (
	"os"
	"path/filepath"
	"testing"
)

func TestDiscoverClassifiesAndSkipsDefaultIgnoredPaths(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "main.go", "package main\n")
	writeFile(t, root, "config.yaml", "name: demo\n")
	writeFile(t, root, "generated/generated.go", "// Code generated by test. DO NOT EDIT.\npackage generated\n")
	writeFile(t, root, "vendor/pkg/vendor.go", "package pkg\n")
	writeFile(t, root, ".goat-flow/tasks/0.1/task.go", "package ignored\n")
	writeFile(t, root, ".goat-flow/logs/session.go", "package ignored\n")

	result, err := Discover(Options{Root: root, Paths: []string{"."}})
	if err != nil {
		t.Fatal(err)
	}

	gotFiles := paths(result.Files)
	wantFiles := []string{"config.yaml", "main.go"}
	if !equal(gotFiles, wantFiles) {
		t.Fatalf("files = %#v, want %#v", gotFiles, wantFiles)
	}

	gotSkipped := skippedReasons(result.Skipped)
	for _, want := range []string{
		"generated/generated.go:generated",
		"vendor:dependency",
		".goat-flow/tasks:goat-flow-local-task-state",
		".goat-flow/logs:goat-flow-local-logs",
	} {
		if !contains(gotSkipped, want) {
			t.Fatalf("skipped reasons %#v missing %q", gotSkipped, want)
		}
	}
}

func TestDiscoverRecordsMissingInputs(t *testing.T) {
	root := t.TempDir()
	result, err := Discover(Options{Root: root, Paths: []string{"missing.go"}})
	if err != nil {
		t.Fatal(err)
	}
	if len(result.Missing) != 1 || result.Missing[0] != "missing.go" {
		t.Fatalf("missing = %#v, want missing.go", result.Missing)
	}
}

func writeFile(t *testing.T, root, rel, contents string) {
	t.Helper()
	path := filepath.Join(root, rel)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
		t.Fatal(err)
	}
}

func paths(files []File) []string {
	out := make([]string, 0, len(files))
	for _, file := range files {
		out = append(out, file.Path)
	}
	return out
}

func skippedReasons(skipped []SkippedPath) []string {
	out := make([]string, 0, len(skipped))
	for _, item := range skipped {
		out = append(out, item.Path+":"+item.Reason)
	}
	return out
}

func equal(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func contains(values []string, value string) bool {
	for _, current := range values {
		if current == value {
			return true
		}
	}
	return false
}
