// Package config emits a default .gruff-go.yaml from the registry catalogue.
// Render walks the supplied rule definitions and writes the canonical YAML shape
// that Load can round-trip, so `gruff-go init` and the interactive bootstrap
// produce a file that already expresses the registry's effective defaults.
package config

import (
	"bytes"
	"fmt"
	"slices"
	"strings"

	"github.com/blundergoat/gruff-go/internal/finding"
	"github.com/blundergoat/gruff-go/internal/rule"
)

// Render returns a default .gruff-go.yaml body that mirrors the registry's
// per-rule enablement, severity, and threshold defaults. The output is sorted
// by rule ID and parses back through Load without modification.
func Render(definitions []rule.Definition) []byte {
	sorted := append([]rule.Definition(nil), definitions...)
	slices.SortFunc(sorted, func(a, b rule.Definition) int { return strings.Compare(a.ID, b.ID) })

	var buf bytes.Buffer
	writeRenderHeader(&buf)
	writeRenderScaffolds(&buf)
	writeRenderRules(&buf, sorted)
	return buf.Bytes()
}

// writeRenderHeader writes the file-level banner and schemaVersion pin.
func writeRenderHeader(buf *bytes.Buffer) {
	fmt.Fprintln(buf, "# gruff-go configuration generated by `gruff-go init`.")
	fmt.Fprintln(buf, "# Edit values to tighten or relax the defaults for this project.")
	fmt.Fprintln(buf, "# Run `gruff-go list-rules --format json` for the live rule catalogue.")
	fmt.Fprintln(buf, "# Fresh start for existing findings: `gruff-go analyse --generate-baseline gruff-baseline.json .`.")
	fmt.Fprintln(buf)
	fmt.Fprintf(buf, "schemaVersion: %q\n", SchemaVersion)
	fmt.Fprintln(buf)
}

// writeRenderScaffolds writes the paths/allowlists/selection sections with
// empty defaults and short comments explaining what each one would do.
func writeRenderScaffolds(buf *bytes.Buffer) {
	fmt.Fprintln(buf, "# Discovery reads .gitignore first. paths.ignore is only for committed")
	fmt.Fprintln(buf, "# metadata, fixtures, or generated artifacts that should stay out of scans")
	fmt.Fprintln(buf, "# even when they are not ignored by Git.")
	fmt.Fprintln(buf, "paths:")
	fmt.Fprintln(buf, "  ignore: []")
	fmt.Fprintln(buf)

	fmt.Fprintln(buf, "# Project-wide allowlists for noisy signals.")
	fmt.Fprintln(buf, "# acceptedAbbreviations relax naming.acronym-case; secretPreviews lists path")
	fmt.Fprintln(buf, "# globs where sensitive-data rules may include the matched preview.")
	fmt.Fprintln(buf, "allowlists:")
	fmt.Fprintln(buf, "  acceptedAbbreviations: []")
	fmt.Fprintln(buf, "  secretPreviews: []")
	fmt.Fprintln(buf)

	fmt.Fprintln(buf, "# Selection narrows the active rule set. Empty lists keep the default")
	fmt.Fprintln(buf, "# selection (every rule below whose `enabled` is true).")
	fmt.Fprintln(buf, "selection:")
	fmt.Fprintln(buf, "  rules: []")
	fmt.Fprintln(buf, "  excludeRules: []")
	fmt.Fprintln(buf, "  pillars: []")
	fmt.Fprintln(buf, "  excludePillars: []")
	fmt.Fprintln(buf)
}

// writeRenderRules writes every rule block under the top-level `rules:` map,
// preserving sort order and emitting the registry's default knobs verbatim.
func writeRenderRules(buf *bytes.Buffer, definitions []rule.Definition) {
	fmt.Fprintln(buf, "rules:")
	for index, definition := range definitions {
		if index > 0 {
			fmt.Fprintln(buf)
		}
		writeRenderRuleBlock(buf, definition)
	}
}

// writeRenderRuleBlock writes one rule entry: a description comment followed
// by enabled, severity, and threshold/thresholds in singular or plural form.
func writeRenderRuleBlock(buf *bytes.Buffer, definition rule.Definition) {
	if definition.Description != "" {
		fmt.Fprintf(buf, "  # %s\n", definition.Description)
	}
	fmt.Fprintf(buf, "  %s:\n", definition.ID)
	fmt.Fprintf(buf, "    enabled: %t\n", definition.DefaultEnabled)
	fmt.Fprintf(buf, "    severity: %s\n", renderSeverityAlias(definition.Severity))
	writeRenderThresholds(buf, definition.Thresholds)
}

// writeRenderThresholds picks the singular `threshold:` form when a rule has
// exactly one knob and the plural `thresholds:` map otherwise. Rules with no
// thresholds emit nothing in this section.
func writeRenderThresholds(buf *bytes.Buffer, thresholds map[string]float64) {
	if len(thresholds) == 0 {
		return
	}
	keys := make([]string, 0, len(thresholds))
	for name := range thresholds {
		keys = append(keys, name)
	}
	slices.Sort(keys)
	if len(keys) == 1 {
		fmt.Fprintf(buf, "    threshold: %s\n", renderThresholdValue(thresholds[keys[0]]))
		return
	}
	fmt.Fprintln(buf, "    thresholds:")
	for _, key := range keys {
		fmt.Fprintf(buf, "      %s: %s\n", key, renderThresholdValue(thresholds[key]))
	}
}

// renderSeverityAlias inverts parseConfigSeverity so the rendered file uses the
// gruff-family aliases (notice/warning/error) that adopters see in docs and
// existing project configs, falling back to the canonical Severity string for
// info and critical which have no alias.
func renderSeverityAlias(severity finding.Severity) string {
	switch severity {
	case finding.SeverityLow:
		return "notice"
	case finding.SeverityMedium:
		return "warning"
	case finding.SeverityHigh:
		return "error"
	default:
		return string(severity)
	}
}

// renderThresholdValue prints whole numbers without the float suffix so the
// rendered file matches the hand-written dogfood config style (`threshold: 80`,
// not `threshold: 80.0`).
func renderThresholdValue(value float64) string {
	if value == float64(int64(value)) {
		return fmt.Sprintf("%d", int64(value))
	}
	return strings.TrimRight(strings.TrimRight(fmt.Sprintf("%f", value), "0"), ".")
}
