// Package rule tests the shared dead-code package reference index.
package rule

import (
	"testing"

	"github.com/blundergoat/gruff-go/internal/finding"
	"github.com/blundergoat/gruff-go/internal/parser"
)

// TestDeadCodePackageReferenceIndexCollectsPrivateSymbols proves the shared index groups packages and declaration kinds without type loading.
func TestDeadCodePackageReferenceIndexCollectsPrivateSymbols(t *testing.T) {
	unit := parseOne(t, "pkg/sample/sample.go", `package sample

type privateType struct{}

const privateConst = 1

var privateVar = privateType{}

func privateFunc() {}
`)
	index := newPackageReferenceIndex([]parser.Unit{unit}, Context{})
	group := index.groups[packageReferenceKey{dir: "pkg/sample", packageName: "sample"}]
	if group == nil {
		t.Fatalf("package group missing: %#v", index.groups)
	}
	if len(group.privateFuncs) != 1 || len(group.privateTypes) != 1 || len(group.privateVars) != 1 || len(group.privateConsts) != 1 {
		t.Fatalf("group = %#v, want one private declaration per kind", group)
	}
}

// TestUnusedPrivateSymbolRulesFlagSimpleCandidates covers the direct positive case for every private-symbol rule.
func TestUnusedPrivateSymbolRulesFlagSimpleCandidates(t *testing.T) {
	unit := parseOne(t, "pkg/sample/sample.go", `package sample

type abandonedType struct{}

var abandonedVar = 1

const abandonedConst = 2
`)
	units := []parser.Unit{unit}
	typeFindings := UnusedPrivateTypeRule{}.AnalyzeProject(units, Context{})
	if len(typeFindings) != 1 || typeFindings[0].Symbol != "abandonedType" {
		t.Fatalf("type findings = %#v, want abandonedType", typeFindings)
	}
	varFindings := UnusedPrivateVarRule{}.AnalyzeProject(units, Context{})
	if len(varFindings) != 1 || varFindings[0].Symbol != "abandonedVar" {
		t.Fatalf("var findings = %#v, want abandonedVar", varFindings)
	}
	constFindings := UnusedPrivateConstRule{}.AnalyzeProject(units, Context{})
	if len(constFindings) != 1 || constFindings[0].Symbol != "abandonedConst" {
		t.Fatalf("const findings = %#v, want abandonedConst", constFindings)
	}
}

// TestUnusedPrivateSymbolRulesResolveCrossFileReferences proves the index suppresses declarations used by sibling files.
func TestUnusedPrivateSymbolRulesResolveCrossFileReferences(t *testing.T) {
	declarations := parseOne(t, "pkg/sample/decl.go", `package sample

type usedType struct{}

var usedVar = 1

const usedConst = 2
`)
	references := parseOne(t, "pkg/sample/use.go", `package sample

func Use() {
	_ = usedType{}
	_ = usedVar
	_ = usedConst
}
`)
	units := []parser.Unit{declarations, references}
	if findings := (UnusedPrivateTypeRule{}).AnalyzeProject(units, Context{}); len(findings) != 0 {
		t.Fatalf("type findings = %#v, want none", findings)
	}
	if findings := (UnusedPrivateVarRule{}).AnalyzeProject(units, Context{}); len(findings) != 0 {
		t.Fatalf("var findings = %#v, want none", findings)
	}
	if findings := (UnusedPrivateConstRule{}).AnalyzeProject(units, Context{}); len(findings) != 0 {
		t.Fatalf("const findings = %#v, want none", findings)
	}
}

// TestUnusedPrivateSymbolRulesSuppressAmbiguousAndUnsafeSurfaces covers parser-only false-positive boundaries.
func TestUnusedPrivateSymbolRulesSuppressAmbiguousAndUnsafeSurfaces(t *testing.T) {
	generated := parseOne(t, "pkg/sample/generated.go", `// Code generated by test; DO NOT EDIT.
package sample

type generatedType struct{}
`)
	testFile := parseOne(t, "pkg/sample/sample_test.go", `package sample

type testHelperType struct{}

var testHelperVar = 1

const testHelperConst = 2
`)
	reflective := parseOne(t, "pkg/reflective/reflective.go", `package reflective

import "reflect"

var _ = reflect.TypeOf

type dispatchedType struct{}
`)
	collision := parseOne(t, "pkg/collision/collision.go", `package collision

var _ = struct {
	collidingName string
}{}

var collidingName = 1
`)
	registry := parseOne(t, "pkg/registry/registry.go", `package registry

var handlers = map[string]func(){}

const (
	firstIota = iota
	secondIota
)
`)
	units := []parser.Unit{generated, testFile, reflective, collision, registry}
	if findings := (UnusedPrivateTypeRule{}).AnalyzeProject(units, Context{}); len(findings) != 0 {
		t.Fatalf("type findings = %#v, want none", findings)
	}
	if findings := (UnusedPrivateVarRule{}).AnalyzeProject(units, Context{}); len(findings) != 0 {
		t.Fatalf("var findings = %#v, want none", findings)
	}
	if findings := (UnusedPrivateConstRule{}).AnalyzeProject(units, Context{}); len(findings) != 0 {
		t.Fatalf("const findings = %#v, want none", findings)
	}
}

// TestUnusedPrivateSymbolRulesShipOptIn confirms candidate rules are available without dominating default scans.
func TestUnusedPrivateSymbolRulesShipOptIn(t *testing.T) {
	for _, definition := range []Definition{
		UnusedPrivateTypeRule{}.Definition(),
		UnusedPrivateVarRule{}.Definition(),
		UnusedPrivateConstRule{}.Definition(),
	} {
		if definition.DefaultEnabled {
			t.Fatalf("%s defaultEnabled = true, want false until calibration proves low noise", definition.ID)
		}
		if definition.Capability != CapabilityParser {
			t.Fatalf("%s capability = %q, want parser", definition.ID, definition.Capability)
		}
		if definition.Severity != finding.SeverityAdvisory {
			t.Fatalf("%s severity = %q, want advisory", definition.ID, definition.Severity)
		}
	}
}
