// Package rule tests documentation checks for suppression comments.
package rule

import (
	"testing"

	"github.com/blundergoat/gruff-go/internal/parser"
	"github.com/blundergoat/gruff-go/internal/source"
)

// TestSuppressionWithoutRationaleRule flags bare nolint and nosec directives.
func TestSuppressionWithoutRationaleRule(t *testing.T) {
	unit := parseOne(t, "suppress.go", `// Package sample is a test package.
package sample

func sample() {
	_ = "token" //nolint:gosec
	_ = "token" // #nosec G101
	_ = "token" //nolint
}
`)
	findings := SuppressionWithoutRationaleRule{}.AnalyzeUnit(unit, Context{})
	if len(findings) != 3 {
		t.Fatalf("findings = %#v, want three bare suppressions", findings)
	}
}

// TestSuppressionWithoutRationaleRuleAcceptsReasons covers common same-line rationale shapes.
func TestSuppressionWithoutRationaleRuleAcceptsReasons(t *testing.T) {
	unit := parseOne(t, "suppress.go", `// Package sample is a test package.
package sample

func sample() {
	_ = "token" //nolint:gosec -- false positive in fixture
	_ = "token" // #nosec G101 -- documented fixture secret
	_ = "token" //nolint:gocyclo // legacy API shape
	// reason: fixture intentionally carries a token-looking string
	_ = "token" //nolint:gosec
	_ = "token" // #nosec G101
	// rationale: fixture secret is not live
}
`)
	findings := SuppressionWithoutRationaleRule{}.AnalyzeUnit(unit, Context{})
	if len(findings) != 0 {
		t.Fatalf("findings = %#v, want none", findings)
	}
}

// TestSuppressionWithoutRationaleRuleAcceptsTextReason covers nearby reasons in non-Go text units.
func TestSuppressionWithoutRationaleRuleAcceptsTextReason(t *testing.T) {
	unit := parser.Unit{
		File:   source.File{Path: "script.sh", Type: source.FileTypeText},
		Source: "# reason: shellcheck false positive in fixture\n#nosec G204\n",
	}
	findings := SuppressionWithoutRationaleRule{}.AnalyzeUnit(unit, Context{})
	if len(findings) != 0 {
		t.Fatalf("findings = %#v, want none", findings)
	}
}

// TestSuppressionWithoutRationaleRuleSkipsGeneratedAndVendor verifies broad default-on exclusions.
func TestSuppressionWithoutRationaleRuleSkipsGeneratedAndVendor(t *testing.T) {
	generated := parseOne(t, "generated.go", `// Code generated by test; DO NOT EDIT.
package sample

func sample() {
	_ = "token" //nolint:gosec
}
`)
	if findings := (SuppressionWithoutRationaleRule{}).AnalyzeUnit(generated, Context{}); len(findings) != 0 {
		t.Fatalf("generated findings = %#v, want none", findings)
	}

	vendor := parseOne(t, "vendor/example/suppress.go", `package sample

func sample() {
	_ = "token" //nolint:gosec
}
`)
	if findings := (SuppressionWithoutRationaleRule{}).AnalyzeUnit(vendor, Context{}); len(findings) != 0 {
		t.Fatalf("vendor findings = %#v, want none", findings)
	}
}
