// Package rule tests the shared rule-level generated-source guard.
package rule

import (
	"testing"

	"github.com/blundergoat/gruff-go/internal/parser"
	"github.com/blundergoat/gruff-go/internal/source"
)

// TestShouldSkipGeneratedUnitIsGoOnly verifies the rule-level generated skip
// applies only to Go units. Discovery skips only generated Go files, so a
// non-Go text unit whose leading comments read like a Go generated banner must
// stay in scope for text rules instead of being silently dropped.
func TestShouldSkipGeneratedUnitIsGoOnly(t *testing.T) {
	banner := "// Code generated by tool; DO NOT EDIT.\n"

	goUnit := parser.Unit{
		File:   source.File{Path: "gen.go", Type: source.FileTypeGo},
		Source: banner + "package sample\n",
	}
	if !shouldSkipGeneratedUnit(goUnit, Context{}) {
		t.Fatal("generated Go unit should be skipped")
	}

	textUnit := parser.Unit{
		File:   source.File{Path: "gen.sql", Type: source.FileTypeText},
		Source: banner + "// next line keeps the header comment-only\n",
	}
	if shouldSkipGeneratedUnit(textUnit, Context{}) {
		t.Fatal("generated-style text unit must stay in scope (skip is Go-only)")
	}
}

// TestShouldSkipGeneratedUnitReleasesWithIncludeIgnored confirms an opted-in run
// scans generated Go files so rule guards match discovery's IncludeIgnored path.
func TestShouldSkipGeneratedUnitReleasesWithIncludeIgnored(t *testing.T) {
	goUnit := parser.Unit{
		File:   source.File{Path: "gen.go", Type: source.FileTypeGo},
		Source: "// Code generated by tool; DO NOT EDIT.\npackage sample\n",
	}
	if shouldSkipGeneratedUnit(goUnit, Context{IncludeIgnored: true}) {
		t.Fatal("IncludeIgnored must release generated Go units back into scope")
	}
}
