// Package rule defines gruff-go's rule registry and analysers.
// This file covers the get-prefix rule's accessor detection and exclusion paths.
package rule

import "testing"

// TestGetPrefixFlagsAccessorMethods verifies the rule flags accessor-shaped Get methods on receivers.
func TestGetPrefixFlagsAccessorMethods(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

type Store struct{}
type User struct{}
type Stats struct{}

func (s Store) GetUser() User { return User{} }
func (s Store) GetCacheStats() (Stats, error) { return Stats{}, nil }
func (s Store) GetUserByID(id string) (User, error) { return User{}, nil }
func (s Store) Get() User { return User{} }
func GetGlobalUser() User { return User{} }
`)
	findings := GetPrefixRule{}.AnalyzeUnit(unit, Context{})
	got := findingSymbols(findings)
	if len(got) != 2 || !got["GetUser"] || !got["GetCacheStats"] {
		t.Fatalf("findings = %#v, want GetUser and GetCacheStats", findings)
	}
}

// TestGetPrefixHonoursExclusions checks both path-based and name-based exclusion lists.
func TestGetPrefixHonoursExclusions(t *testing.T) {
	unit := parseOne(t, "pkg/service.pb.go", `package pkg

type Store struct{}
type User struct{}

func (s Store) GetUser() User { return User{} }
`)
	if got := (GetPrefixRule{ExcludePaths: []string{"**/*.pb.go"}}).AnalyzeUnit(unit, Context{}); len(got) != 0 {
		t.Fatalf("excluded path should pass, got %#v", got)
	}
	if got := (GetPrefixRule{ExcludeNames: []string{"GetUser"}}).AnalyzeUnit(unit, Context{}); len(got) != 0 {
		t.Fatalf("excluded name should pass, got %#v", got)
	}
}

// TestGetPrefixSkipsGeneratedFiles asserts machine-generated files are excluded from analysis.
func TestGetPrefixSkipsGeneratedFiles(t *testing.T) {
	unit := parseOne(t, "pkg/generated.go", `// Code generated by tool; DO NOT EDIT.
package pkg

type Store struct{}
type User struct{}

func (s Store) GetUser() User { return User{} }
`)
	if got := (GetPrefixRule{}).AnalyzeUnit(unit, Context{}); len(got) != 0 {
		t.Fatalf("generated file should pass, got %#v", got)
	}
}

// TestGetPrefixFlagsContextAccessorFunctions asserts the rule also catches the
// context-value accessor pattern (`GetLogger(ctx)`) at free-function scope.
// Other free-function shapes — including zero-param `GetGlobal` and variadic
// or multi-param signatures — must remain unflagged.
func TestGetPrefixFlagsContextAccessorFunctions(t *testing.T) {
	unit := parseOne(t, "pkg/ctx.go", `package pkg

import "context"

type Logger struct{}
type RequestID string
type Config struct{}

func GetLogger(ctx context.Context) *Logger { return nil }
func GetRequestID(ctx context.Context) RequestID { return "" }
func GetConfig(ctx context.Context) (Config, error) { return Config{}, nil }

// Free functions outside the new pattern stay untouched:
func GetGlobalLogger() *Logger { return nil }
func GetByID(ctx context.Context, id string) *Logger { return nil }
func GetMany(ctx context.Context) (*Logger, *Logger, error) { return nil, nil, nil }
`)
	findings := GetPrefixRule{}.AnalyzeUnit(unit, Context{})
	got := findingSymbols(findings)
	want := map[string]bool{"GetLogger": true, "GetRequestID": true, "GetConfig": true}
	for name := range want {
		if !got[name] {
			t.Errorf("expected %s to be flagged", name)
		}
	}
	for name := range got {
		if !want[name] {
			t.Errorf("unexpected finding for %s", name)
		}
	}
}

// TestGetPrefixIsDefaultEnabled confirms the rule is enabled by default with parser capability.
func TestGetPrefixIsDefaultEnabled(t *testing.T) {
	if !(GetPrefixRule{}).Definition().DefaultEnabled {
		t.Error("naming.get-prefix must be default-enabled")
	}
	if (GetPrefixRule{}).Definition().Capability != CapabilityParser {
		t.Error("naming.get-prefix must be parser-capability")
	}
}
