package rule

import "testing"

func TestGetPrefixFlagsAccessorMethods(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

type Store struct{}
type User struct{}
type Stats struct{}

func (s Store) GetUser() User { return User{} }
func (s Store) GetCacheStats() (Stats, error) { return Stats{}, nil }
func (s Store) GetUserByID(id string) (User, error) { return User{}, nil }
func (s Store) Get() User { return User{} }
func GetGlobalUser() User { return User{} }
`)
	findings := GetPrefixRule{}.AnalyzeUnit(unit, Context{})
	got := findingSymbols(findings)
	if len(got) != 2 || !got["GetUser"] || !got["GetCacheStats"] {
		t.Fatalf("findings = %#v, want GetUser and GetCacheStats", findings)
	}
}

func TestGetPrefixHonoursExclusions(t *testing.T) {
	unit := parseOne(t, "pkg/service.pb.go", `package pkg

type Store struct{}
type User struct{}

func (s Store) GetUser() User { return User{} }
`)
	if got := (GetPrefixRule{ExcludePaths: []string{"**/*.pb.go"}}).AnalyzeUnit(unit, Context{}); len(got) != 0 {
		t.Fatalf("excluded path should pass, got %#v", got)
	}
	if got := (GetPrefixRule{ExcludeNames: []string{"GetUser"}}).AnalyzeUnit(unit, Context{}); len(got) != 0 {
		t.Fatalf("excluded name should pass, got %#v", got)
	}
}

func TestGetPrefixSkipsGeneratedFiles(t *testing.T) {
	unit := parseOne(t, "pkg/generated.go", `// Code generated by tool; DO NOT EDIT.
package pkg

type Store struct{}
type User struct{}

func (s Store) GetUser() User { return User{} }
`)
	if got := (GetPrefixRule{}).AnalyzeUnit(unit, Context{}); len(got) != 0 {
		t.Fatalf("generated file should pass, got %#v", got)
	}
}

func TestGetPrefixIsDefaultEnabled(t *testing.T) {
	if !(GetPrefixRule{}).Definition().DefaultEnabled {
		t.Error("naming.get-prefix must be default-enabled")
	}
	if (GetPrefixRule{}).Definition().Capability != CapabilityParser {
		t.Error("naming.get-prefix must be parser-capability")
	}
}
