package rule

import "testing"

func TestAcronymCaseFlagsMixedCaseInitialisms(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

type HttpClient struct {
	UrlParser  string
	HTTPClient string
}

type IdGenerator struct{}

func JsonReport(url URLParser) {
	var userId = 1
	_ = userId
}

type URLParser struct{}

var AwsRegion = "us-east-1"

const JwtToken = "token"
`)
	findings := AcronymCaseRule{}.AnalyzeUnit(unit, Context{})
	got := findingSymbols(findings)
	want := []string{"HttpClient", "UrlParser", "IdGenerator", "JsonReport", "userId", "AwsRegion", "JwtToken"}
	for _, symbol := range want {
		if !got[symbol] {
			t.Fatalf("findings = %#v, want symbol %q", findings, symbol)
		}
	}
	if got["HTTPClient"] || got["URLParser"] {
		t.Fatalf("correctly cased acronyms should not be flagged; got %#v", findings)
	}
	if len(got) != len(want) {
		t.Fatalf("findings = %#v, want exactly %v", findings, want)
	}
}

func TestAcronymCaseAllowsConsistentCase(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

type HTTPClient struct {
	URLParser string
}

type IDGenerator struct{}

func JSONReport(urlParser URLParser) {
	userID := 1
	jwtToken := "token"
	_ = userID
	_ = jwtToken
}

type URLParser struct{}
`)
	findings := AcronymCaseRule{}.AnalyzeUnit(unit, Context{})
	if len(findings) != 0 {
		t.Fatalf("consistent acronym casing should pass, got %#v", findings)
	}
}

func TestAcronymCaseHonoursAllowAndAcceptedAbbreviations(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

type HttpClient struct{}
type UrlParser struct{}
type JsonReport struct{}
`)
	rule := AcronymCaseRule{
		Allow:                 []string{"HttpClient"},
		AcceptedAbbreviations: []string{"URL"},
	}
	findings := rule.AnalyzeUnit(unit, Context{})
	if len(findings) != 1 || findings[0].Symbol != "JsonReport" {
		t.Fatalf("expected only JsonReport after allowlists, got %#v", findings)
	}
}

func TestAcronymCaseSupportsConfiguredAcronyms(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

type UuidStore struct{}
type UUIDCache struct{}
type HttpClient struct{}
`)
	rule := AcronymCaseRule{Acronyms: []string{"UUID"}}
	findings := rule.AnalyzeUnit(unit, Context{})
	if len(findings) != 1 || findings[0].Symbol != "UuidStore" {
		t.Fatalf("expected only configured UUID acronym finding, got %#v", findings)
	}
}

func TestAcronymCaseSkipsGeneratedFiles(t *testing.T) {
	unit := parseOne(t, "pkg/generated.go", `// Code generated by tool; DO NOT EDIT.
package pkg

type HttpClient struct{}
`)
	findings := AcronymCaseRule{}.AnalyzeUnit(unit, Context{})
	if len(findings) != 0 {
		t.Fatalf("generated file should be skipped, got %#v", findings)
	}
}

func TestAcronymCaseIsDefaultEnabled(t *testing.T) {
	if !(AcronymCaseRule{}).Definition().DefaultEnabled {
		t.Error("naming.acronym-case must be default-enabled")
	}
	if (AcronymCaseRule{}).Definition().Capability != CapabilityParser {
		t.Error("naming.acronym-case must be parser-capability")
	}
}
