// Package rule defines gruff-go's rule registry and analysers.
// This file exercises the contextual-generic rule's size-gated detection logic.
package rule

import "testing"

// TestContextualGenericIgnoresShortGenericRange confirms generic range names are tolerated in short loops.
func TestContextualGenericIgnoresShortGenericRange(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

func Render(users []string) {
	for _, item := range users {
		println(item)
	}
}
`)
	findings := (ContextualGenericRule{MinBodyLines: 3}).AnalyzeUnit(unit, Context{})
	if len(findings) != 0 {
		t.Fatalf("short loop should pass, got %#v", findings)
	}
}

// TestContextualGenericFlagsLongGenericRange checks the rule emits a finding when the body crosses the line gate.
func TestContextualGenericFlagsLongGenericRange(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

func Render(users []string) {
	for _, item := range users {
		println(item)
		println(item)
		println(item)
		println(item)
		println(item)
		println(item)
	}
}
`)
	findings := (ContextualGenericRule{MinBodyLines: 5}).AnalyzeUnit(unit, Context{})
	if len(findings) != 1 || findings[0].Symbol != "item" {
		t.Fatalf("findings = %#v, want one item finding", findings)
	}
	if findings[0].Metadata["range"] != "users" {
		t.Fatalf("metadata = %#v, want range users", findings[0].Metadata)
	}
}

// TestContextualGenericHonoursConfiguredGenericNames verifies user-supplied generic name lists override defaults.
func TestContextualGenericHonoursConfiguredGenericNames(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

func Render(records []string) {
	for _, record := range records {
		println(record)
		println(record)
	}
}
`)
	defaultFindings := (ContextualGenericRule{MinBodyLines: 1}).AnalyzeUnit(unit, Context{})
	if len(defaultFindings) != 0 {
		t.Fatalf("record is not a default generic name, got %#v", defaultFindings)
	}
	configured := (ContextualGenericRule{
		GenericNames: []string{"record"},
		MinBodyLines: 1,
	}).AnalyzeUnit(unit, Context{})
	if len(configured) != 1 || configured[0].Symbol != "record" {
		t.Fatalf("configured findings = %#v, want record", configured)
	}
}

// TestContextualGenericFlagsAccumulatorsOnlyWhenGatesPass exercises both the function-length and require-multiple gates.
func TestContextualGenericFlagsAccumulatorsOnlyWhenGatesPass(t *testing.T) {
	unit := parseOne(t, "pkg/file.go", `package pkg

func Build(users []string) []string {
	out := []string{}
	result := []string{}
	for _, user := range users {
		out = append(out, user)
		result = append(result, user)
	}
	return append(out, result...)
}

func Single(users []string) []string {
	out := []string{}
	for _, user := range users {
		out = append(out, user)
	}
	return out
}
`)
	findings := (ContextualGenericRule{
		MinFunctionLines: 3,
	}).AnalyzeUnit(unit, Context{})
	got := findingSymbols(findings)
	if len(got) != 2 || !got["out"] || !got["result"] {
		t.Fatalf("findings = %#v, want out and result from Build only", findings)
	}

	allowSingle := false
	singleFindings := (ContextualGenericRule{
		MinFunctionLines: 3,
		RequireMultiple:  &allowSingle,
	}).AnalyzeUnit(unit, Context{})
	if len(singleFindings) != 3 {
		t.Fatalf("single-allowed findings = %#v, want three accumulator findings", singleFindings)
	}
}

// TestContextualGenericSkipsTestAndGeneratedFiles ensures the rule ignores test and machine-generated files.
func TestContextualGenericSkipsTestAndGeneratedFiles(t *testing.T) {
	testUnit := parseOne(t, "pkg/file_test.go", `package pkg

func TestRender() {
	for _, item := range []string{"a"} {
		println(item)
		println(item)
	}
}
`)
	if got := (ContextualGenericRule{MinBodyLines: 1}).AnalyzeUnit(testUnit, Context{}); len(got) != 0 {
		t.Fatalf("test file should pass, got %#v", got)
	}

	generatedUnit := parseOne(t, "pkg/generated.go", `// Code generated by tool; DO NOT EDIT.
package pkg

func Render(users []string) {
	for _, item := range users {
		println(item)
		println(item)
	}
}
`)
	if got := (ContextualGenericRule{MinBodyLines: 1}).AnalyzeUnit(generatedUnit, Context{}); len(got) != 0 {
		t.Fatalf("generated file should pass, got %#v", got)
	}
}

// TestContextualGenericIsDefaultEnabled asserts the rule ships on by default and runs at parser capability.
func TestContextualGenericIsDefaultEnabled(t *testing.T) {
	definition := ContextualGenericRule{}.Definition()
	if !definition.DefaultEnabled {
		t.Error("naming.contextual-generic must be default-enabled")
	}
	if definition.Capability != CapabilityParser {
		t.Error("naming.contextual-generic must be parser-capability")
	}
}
