// Package rule tests additional parser-only security hardening rules.
package rule

import "testing"

// TestHTTPServerNoTimeoutRule covers server literals and direct helpers.
func TestHTTPServerNoTimeoutRule(t *testing.T) {
	tests := []struct {
		name string
		file string
		code string
		want int
	}{
		{
			name: "server literal without timeout",
			file: "server.go",
			code: `// Package sample is a test package.
package sample

import "net/http"

func server() *http.Server {
	return &http.Server{Addr: ":8080"}
}
`,
			want: 1,
		},
		{
			name: "listen and serve helper",
			file: "server.go",
			code: `// Package sample is a test package.
package sample

import "net/http"

func serve() error {
	return http.ListenAndServe(":8080", nil)
}
`,
			want: 1,
		},
		{
			name: "server with read header timeout",
			file: "server.go",
			code: `// Package sample is a test package.
package sample

import (
	"net/http"
	"time"
)

func server() http.Server {
	return http.Server{Addr: ":8080", ReadHeaderTimeout: 5 * time.Second}
}
`,
			want: 0,
		},
		{
			name: "test file skipped",
			file: "server_test.go",
			code: `package sample

import "net/http"

func server() http.Server {
	return http.Server{}
}
`,
			want: 0,
		},
		{
			name: "generated file skipped",
			file: "generated.go",
			code: `// Code generated by test; DO NOT EDIT.
package sample

import "net/http"

func server() http.Server {
	return http.Server{}
}
`,
			want: 0,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			unit := parseOne(t, tt.file, tt.code)
			findings := HTTPServerNoTimeoutRule{}.AnalyzeUnit(unit, Context{})
			if len(findings) != tt.want {
				t.Fatalf("findings = %#v, want %d", findings, tt.want)
			}
		})
	}
}

// TestPermissiveFileModeRule covers world-writable modes and safe conservative modes.
func TestPermissiveFileModeRule(t *testing.T) {
	tests := []struct {
		name string
		file string
		code string
		want int
	}{
		{
			name: "open file world writable",
			file: "files.go",
			code: `// Package sample is a test package.
package sample

import "os"

func writeFile() {
	_, _ = os.OpenFile("secret.txt", os.O_CREATE|os.O_WRONLY, 0666)
}
`,
			want: 1,
		},
		{
			name: "open file world executable",
			file: "files.go",
			code: `// Package sample is a test package.
package sample

import "os"

func writeFile() {
	_, _ = os.OpenFile("script.sh", os.O_CREATE|os.O_WRONLY, 0755)
}
`,
			want: 1,
		},
		{
			name: "mkdir world writable",
			file: "files.go",
			code: `// Package sample is a test package.
package sample

import "os"

func mkdir() {
	_ = os.MkdirAll("cache", 0o777)
}
`,
			want: 1,
		},
		{
			name: "mode perm selector",
			file: "files.go",
			code: `// Package sample is a test package.
package sample

import "os"

func chmod() {
	_ = os.Chmod("cache", os.ModePerm)
}
`,
			want: 1,
		},
		{
			name: "safe file and directory modes",
			file: "files.go",
			code: `// Package sample is a test package.
package sample

import "os"

func safe() {
	_, _ = os.OpenFile("secret.txt", os.O_CREATE|os.O_WRONLY, 0600)
	_ = os.MkdirAll("bin", 0755)
	_ = os.Chmod("public.txt", 0644)
}
`,
			want: 0,
		},
		{
			name: "test file skipped",
			file: "files_test.go",
			code: `package sample

import "os"

func fixture() {
	_ = os.MkdirAll("fixture", 0777)
}
`,
			want: 0,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			unit := parseOne(t, tt.file, tt.code)
			findings := PermissiveFileModeRule{}.AnalyzeUnit(unit, Context{})
			if len(findings) != tt.want {
				t.Fatalf("findings = %#v, want %d", findings, tt.want)
			}
		})
	}
}
