package analysis

import (
	"strings"
	"testing"

	"github.com/blundergoat/gruff-go/internal/finding"
	"github.com/blundergoat/gruff-go/internal/rule"
)

// TestAnalyzeExplicitAllSkippedInputReportsDiagnostic ensures skipped explicit
// paths do not masquerade as a clean zero-file scan.
func TestAnalyzeExplicitAllSkippedInputReportsDiagnostic(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "generated.go", "// Code generated by fixture. DO NOT EDIT.\npackage generated\n")
	t.Chdir(root)

	report, err := Analyze(Options{
		Paths:                  []string{"generated.go"},
		Registry:               rule.Defaults(),
		FailOn:                 finding.FailThresholdNone,
		ReportAllSkippedInputs: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if report.Summary.ExitCode != 2 {
		t.Fatalf("exit code = %d, want 2", report.Summary.ExitCode)
	}
	if len(report.Diagnostics) != 1 {
		t.Fatalf("diagnostics = %#v, want one all-skipped diagnostic", report.Diagnostics)
	}
	diagnostic := report.Diagnostics[0]
	if diagnostic.Stage != "discovery" || diagnostic.File != "generated.go" {
		t.Fatalf("diagnostic = %#v, want discovery diagnostic for explicit generated path", diagnostic)
	}
	if !strings.Contains(diagnostic.Message, "explicit input skipped before parsing") ||
		!strings.Contains(diagnostic.Message, "source=generated") ||
		!strings.Contains(diagnostic.Message, "--include-ignored") {
		t.Fatalf("diagnostic message missing remediation detail: %q", diagnostic.Message)
	}
}

// TestAnalyzeIncludeIgnoredScansGeneratedRuleGuards proves --include-ignored
// opts into generated files in both discovery and rule-level generated guards.
func TestAnalyzeIncludeIgnoredScansGeneratedRuleGuards(t *testing.T) {
	root := t.TempDir()
	writeFile(t, root, "generated_test.go", `// Generated by test harness. DO NOT EDIT.
package generated

import "time"

func TestGeneratedSleep() {
	time.Sleep(time.Second)
}
`)
	t.Chdir(root)

	defaultReport, err := Analyze(Options{
		Paths:    []string{"."},
		Registry: rule.Defaults(),
		FailOn:   finding.FailThresholdNone,
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(defaultReport.Paths.Scanned) != 0 {
		t.Fatalf("default scan should skip generated file, scanned %#v", defaultReport.Paths.Scanned)
	}
	if len(defaultReport.Paths.Skipped) != 1 || defaultReport.Paths.Skipped[0].Reason != "generated" {
		t.Fatalf("default scan skipped paths = %#v, want generated skip", defaultReport.Paths.Skipped)
	}

	includeReport, err := Analyze(Options{
		Paths:          []string{"."},
		Registry:       rule.Defaults(),
		FailOn:         finding.FailThresholdNone,
		IncludeIgnored: true,
	})
	if err != nil {
		t.Fatal(err)
	}
	if !hasString(includeReport.Paths.Scanned, "generated_test.go") {
		t.Fatalf("include-ignored scan should parse generated file, scanned %#v", includeReport.Paths.Scanned)
	}
	if !containsRuleID(includeReport.Findings, "test-quality.sleep-in-test") {
		t.Fatalf("include-ignored generated test should produce sleep finding, got %#v", includeReport.Findings)
	}
}
